config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
  end

  root 'welcome#index'

  namespace :admin do
    resources :entries do
      get 'clone', on: :member
      get 'import', on: :member
      resources :items
      resource :download, only: [:show]
    end
    # TODO scope routes
    resources :settings
    resources :customers
    resources :summaries
    resources :bills
    resources :versions do
      collection do
        get 'remove_all'
      end
    end
  end

end

app/models/summary.rb
class Entry < ActiveRecord::Base
  has_paper_trail :ignore => [:created_at, :updated_at]
  has_many :items, -> { order 'items.sort'}
  belongs_to :customer

  accepts_nested_attributes_for :items, allow_destroy: true
  accepts_nested_attributes_for :customer

  after_update :sanitize
  before_save :default_values
  after_initialize :init

  scope :visible, -> { 
    where.not("is_offer", true).where("status" => "paid")
  }
  def init
    self.invoice_date ||= Date.today
    self.delivery_date ||= Date.today
    self.invoice_number ||= Time.now.to_i
  end

  def default_values
    if self.title.nil? || self.title.empty?
      if self.customer.present?
        self.title = self.customer.name
      else
        self.title = self.invoice_number
      end
    end
  end

  def sanitize
    self.notes = self[:notes].gsub("\n", '').squeeze(' ') if self[:notes].present?
    self.private_note = self[:private_note].gsub("\n", '').squeeze(' ') if self[:private_note].present?
  end

  def self.total
    self.collect { |x| x.items.collect{|y| y.price.to_f}.reduce(0, :+) }
  end

end

app/controllers/admin/summaries_controller.rb
module Admin
  class SummariesController < ApplicationController

    include ApplicationHelper
    include ActionView::Helpers::NumberHelper
    include EntriesHelper
    before_action :authenticate_user!

    def index
      @year_group = Entry.visible.group_by { |u| u.delivery_date.beginning_of_year }
      @bills = Bill.all.group_by { |u| u.bill_date.beginning_of_year }
      @total = []
      @year_group.each_with_index do |year, index|
        entries = Entry.visible.where(:delivery_date => year[0].beginning_of_year..year[0].end_of_year)
        @total << {
          year: year[0].year,
          entries: entries.collect{ |x|  get_tax_items_total(x)}.inject(0, :+),
          bills: Bill.where(:bill_date => year[0].beginning_of_year..year[0].end_of_year).sum(:price),
          taxes: { 
            consultant: entries.where(:is_consultant => 1).count,
            without_consultant: year[1].count - entries.where(:is_consultant => 1).count,
            taxes: entries.where.not(:is_consultant => 1).collect{ |x|  get_tax_items_total(x)}.inject(0, :+)
          }
        }
      end

    end

    def new
      @summary = Summary.new
      @items = @summary.items.build
      @customer = @summary.customer || Customer.new
      render 'edit'
    end

    def edit
      @summary = Summary.find(params[:id])
      @item = Item.new
      @customer = @summary.customer || Customer.new
      @title = "edit #{@summary.title} | Zelos"
      @time = "#{ @summary.items.collect{|x| x.count}.reduce(0, :+) / 60 }:#{@summary.items.collect{|x| x.count}.reduce(0, :+) % 60} H"
    end

    def clone
      summary = Summary.find(params[:id])
      @summary = summary.dup
      @summary.invoice_number = Time.now.to_i
      @summary.title = "#{summary.title} Duplicate"
      @summary.save
      summary.items.each do |item|
        @summary.items.create(item.dup.attributes)
      end
      @item = Item.new
      flash.now[:notice] = 'Summary cloned!'
      redirect_to edit_admin_summary_path(@summary)
    end

    def show
      redirect_to action: "edit"
    end

    def update
      @summary = Summary.find(params[:id])
      if summary_params["customer_attributes"]["id"].present?
        @customer = Customer.find(summary_params["customer_attributes"]["id"])
        @summary.customer = @customer
      end

      if @summary.update_attributes(summary_params)
        flash[:notice] = 'Summary has been saved successfully!'
      else
        flash[:error] = @summary.errors.full_messages.first.to_s
      end

      redirect_to edit_admin_summary_path(@summary)
    end

    def create
      @summary = Summary.new
      if @summary.save
        if summary_params["customer_attributes"]["id"].present?
          @customer = Customer.find(summary_params["customer_attributes"]["id"])
          @summary.customer = @customer
        end
        @summary.update_attributes(summary_params)
        flash.now[:success] = 'Summary has been created successfully!'
        @summaries = Summary.all
        redirect_to edit_admin_summary_path(@summary)
      else
        flash.now[:error] = 'There was a problem :('
      end
    end

    def destroy
      @summary = Summary.find(params[:id])
      @summary.items.destroy_all
      if @summary.destroy
        flash[:notice] = 'Summary destroyed!'
      else
        flash[:error] = 'There was a problem :('
      end
      @summaries = Summary.all

      redirect_to action: :index
    end

    private

    def summary_params
      params.require(:summary)
        .permit(:title, :invoice_number, :invoice_date, :delivery_date, :notes, :private_note, :discount, :company, :is_offer, :is_consultant, :valid_until, :status, customer_attributes: [:id, :name, :address, :company],  items_attributes: [:name, :price, :count_hours, :count_mins, :_destroy, :id])
    end
  end
end

app/views/admin/summaries/_footer.haml
%h1 Footer

app/views/admin/summaries/_tree.html.haml
.row.hide-on-med-and-down.mt-2
  .col.s6
    %h5 Invoices per year 
    = column_chart Entry.visible.group_by_year(:delivery_date).count, colors: ["#27ae60"]
  .col.s6
    %h5 Bills per year 
    = column_chart Bill.group_by_year(:bill_date).count, colors: ["#F44336"]
  -#.col.s4
    -#- bla = Entry.visible.group_by_year(:delivery_date)

    -#- networth_data = [ {name: "Assets", data: {"NetWorth": 6979.53}}, {name: "Liabilities", data: {"NetWorth": 10532.32}} ]

    -#- networth_data = []
    -#- binding.pry
    -#- bla.each do |year|
      -#- networth_data << { {name: year, data: {"Money": 6979.53}}, {name: "Liabilities", data: {"Money": 10532.32}} }
    
    -#= column_chart networth_data, colors: ["green", "#FF0000"], library: {backgroundColor: "#FFF", height: 500}
%hr
%table.highlight
  %thead.no-border
    %tr
      %th.hide-on-med-and-down Year
      %th.hide-on-med-and-down Income
      %th.hide-on-med-and-down Bills
      %th.hide-on-med-and-down Profit
      %th.hide-on-med-and-down Taxes

  %tbody
    -@total.each_with_index do |year, index|
      %tr
        %td
          = year[:year]
        %td
          %span.green-text= money_helper( year[:entries])
        %td
          - if year[:bills].present?
            %span.red-text= money_helper( year[:bills] )
        %td
          = money_helper( year[:entries] - year[:bills] ) 
        %td

          .btn.btn-sm.px-1
            = "#{ year[:taxes][:consultant] }"
            %i.material-icons
              local_library  
          .btn.btn-sm.px-1
            = "#{ year[:taxes][:without_consultant] }"
            %i.material-icons
              code  
          = money_helper(year[:taxes][:taxes])
          %span.red-text.right
            Taxes: 
            = money_helper(year[:taxes][:taxes] / 100 * 19)

app/views/admin/summaries/edit.html.haml
- if ["new", "clone"].include?(action_name)
  - path = admin_entries_path
- elsif action_name == "edit"
  - path = admin_entry_path(@entry)
%section.container.row.full-width.no-max-width
  .col.s12
    = form_for(@entry, url: path) do |f|

      .section.row
        .col.m6.s12
          .row.mb-3
            .col.m4.switch
              %label
                Paid?
                = f.check_box(:status, { class: '' }, "paid", "open")
                %span.lever
            .col.m4.switch
              %label
                Offer?
                = f.check_box :is_offer, checked: params[:is_offer] == "true" ||  @entry.is_offer?
                %span.lever
            .col.m4.switch
              %label
                Consultant?
                = f.check_box :is_consultant, checked: params[:is_consultant] == "true" ||  @entry.is_consultant?
                %span.lever

          .input-field
            %h5
              = f.label :title, class: action_name == "edit" ? "active" : ""
            = f.text_field :title, class: "validate", :autofocus => true, :required => true

          = f.fields_for :customer, @customer do |builder|

            = builder.hidden_field :id
            .input-field.pb-1
              - if ["new", "clone"].exclude?(action_name)
                %i.material-icons{class: @entry.customer.present? ? "prefix" : ""} 
                  - if @entry.customer.present?
                    = link_to edit_admin_customer_path(@customer) do
                      account_circle
              = builder.label :name, "Customer Name", class: @entry.customer.present? ? "active" : "", :required => true
              = builder.text_field :name, class: "validate autocomplete", value: @entry.customer.present? ? @entry.customer.name : nil
            .input-field
              = builder.label :address, "Customer Address", class: @entry.customer.present? ? "active" : ""
              = builder.text_area :address, class: "validate materialize-textarea"
            .input-field
              = builder.label :company, "Company", class: @entry.customer.present? ? "active" : ""
              = builder.text_field :company, class: "validate"


        .col.m6.s12
          .input-field
            = f.label :invoice_number, class: "active" 
            = f.number_field :invoice_number, class: "validate"
          .input-field.row.mt-0.pb-1
            .col.s6.input-field
              = f.label :invoice_date, class: "active"
              = f.date_field :invoice_date, class: "validate datepicker mb-0"
            .col.s6.input-field
              = f.label :delivery_date, class: "active"
              = f.date_field :delivery_date, class: "validate mb-0"

          %ul.box-shadow-0.m-0.collapsible{"data-collapsible" => "expandable"}
            %li
              .collapsible-header.hiddendiv{class: @entry.is_offer? || params[:is_offer] ? "active": ""}
              .collapsible-body.pr-0.pl-0.pb-0.no-border.pt-0
                .input-field
                  = f.label :valid_until, class: action_name == "edit" ? "active" : ""
                  = f.date_field :valid_until, class: "validate datepicker "

          .input-field
            .row.mb-0
              .col.s10
                = f.label :notes, class: (action_name == "edit" && @entry.notes.present?) ? "active" : ""
                = f.text_area :notes, class: "materialize-textarea validate", value: (( action_name == "edit" && @entry.notes.present?) ? @entry.notes.gsub("\n", '').squeeze(' ') : "")
              .col.s2
                .row.mb-0
                  .col.p-0
                    %a.right.btn-floating.tooltipped.mb-1.note-part.waves-effect.waves-light.btn{"data-delay": 10, "data-position":"left", "data-tooltip": "Ich bin nach §19 UStG als Kleinunternehmer von der Umsatzsteuer befreit.", "data-value": "Ich bin nach §19 UStG als Kleinunternehmer von der Umsatzsteuer befreit."}
                      %i.material-icons child_care
                .row.mb-0
                  .col.p-0
                    %a.right.btn-floating.tooltipped.mb-1.note-part.waves-effect.waves-light.btn{"data-delay": 10, "data-position":"left", "data-tooltip": "Diese Tätigkeit ist nach §4 Nr. 21 UstG von der Umsatzsteuer für Bildungsleistungen befreit.", "data-value": "Diese Tätigkeit ist nach §4 Nr. 21 UstG von der Umsatzsteuer für Bildungsleistungen befreit."}
                      %i.material-icons change_history

          .input-field
            .row.mb-0
              .col.s12
                = f.label :private_note, class: (action_name == "edit" && @entry.private_note.present?) ? "active" : ""
                = f.text_area :private_note, class: "materialize-textarea validate", value: ((action_name == "edit" && @entry.private_note.present?) ? @entry.private_note.gsub("\n", '').squeeze(' ') : "")
        
        
      .section
        %h4 Items
        .row.mb-5
          .sortable
            = f.nested_fields_for :items, @items, wrapper_options: { class: 'm-0 no-border no-padding' } do |ff|
              %span.hiddendiv.nested_index= ff.object.id

              .input-field.col.m7.s12
                = ff.label "Activity", class: "active"
                = ff.text_field :name, :required => true, class: "validate mb-0"
              .col.s5.m2.inline
                .row
                  .col.s6.input-field
                    = ff.label "Hour", class: "active" 
                    = ff.number_field :count_hours, class: "validate mb-0"
                  .col.s6.input-field
                    = ff.label "Min", class: "active" 
                    = ff.number_field :count_mins, max: 60, min: 0, placeholder: 0, class: "validate mb-0"
              .input-field.col.s5.m2
                = ff.label "Price",class: "active" 
                = ff.number_field :price, step: 0.01, :required => true, class: "validate mb-0"
              .col.s2.m1.text-right
                .right
                  = ff.remove_nested_fields_link do
                    .btn-floating.waves-effect.waves-light.red.mt-1
                      %i.material-icons remove

          .col.s12
            .row.mb-0
              .col.m7
                = f.add_nested_fields_link :items, class: "tooltipped btn-floating waves-effect waves-light big-when-focus", "data-delay": 10, "data-position":"right", "data-tooltip": "Add Item" do
                  %i.material-icons add
              .col.s6.m2
                .input-field
                  = f.label "discount",class: action_name == "edit" ? "active" : ""
                  = f.number_field :discount, class: "validate"
              .col.s6.m3.teal-text
                Total:
                %div= @time
                %div= "#{money_helper(get_items_total( @entry ))}"
              
            
      .fixed-action-btn
        = f.button :submit, class: "pulse tooltipped btn btn-floating btn-large ", "data-delay": 10, "data-position":"left", "data-tooltip": "Save" do
          %i.material-icons done

        - if action_name == "edit"

          %ul
            %li
              = link_to admin_entry_download_path(@entry), target: "_blank", class: "tooltipped btn btn-floating", "data-delay": 10, "data-position":"left", "data-tooltip": "Preview" do
                %i.material-icons="open_in_browser"
            %li
              = link_to admin_entry_download_path(@entry, format: "pdf"), target: "_blank", class: "tooltipped btn btn-floating yellow darken-2", "data-delay": 10, "data-position":"left", "data-tooltip": "Download", "data-value": "Ich bin nach §19 UStG als Kleinunternehmer von der Umsatzsteuer befreit." do
                %i.material-icons="play_for_work"

app/views/admin/summaries/index.html.haml
- if @year_group.any? && @bills.any?
  .row
    #summaries_tree
      = render "tree"
- else
  %h2.grey-text.text-lighten-1.center-align.mt-5
    %div
      %i.material-icons.large.grey-text.text-lighten-1 child_care
    =t('all_good')


.fixed-action-btn
  = link_to new_admin_summary_path, class: "btn-floating waves-effect waves-light green btn-large" do
    %i.new_button.material-icons.large add
  %ul
    %li
      = link_to new_admin_summary_path(:is_offer => true), class: "btn-floating waves-effect waves-light red" do
        %i.material-icons question_answer