config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
  end

  root 'welcome#index'

  namespace :admin do
    resources :entries do
      get 'clone', on: :member
      get 'import', on: :member
      resources :items
      resource :download, only: [:show]
    end
    # TODO scope routes
    resources :settings
    resources :customers
    resources :summaries
    resources :bills
    resources :versions do
      collection do
        get 'remove_all'
      end
    end
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_paper_trail :ignore => [:created_at, :updated_at]
  has_many :entries, :dependent => :nullify
  validates :name, presence: true
  before_validation :strip_whitespace

  def strip_whitespace
    self.name = self.name.strip unless self.name.nil?
    self.address = self[:address].gsub("\n", '').squeeze(' ') unless self.address.nil?
  end

end

app/controllers/admin/customers_controller.rb
module Admin
  class CustomersController < ApplicationController
    include EntriesHelper

    before_action :authenticate_user!

    def index
      @customers = Customer.all.order('name asc')
      @grouped_customers = @customers.group_by{|x| x.name[0,1]}
      @customer_count = Customer.all.map{|e| e.entries.count}.max
      @title = "Customers"
      unless params[:search].blank?
        @customers = Customer.where(:name => params[:search]).order('name asc')
        @grouped_customers = @customers.group_by{|x| x.name[0,1]}
      end
      respond_to do |format|
        format.html {
          if @customers.length == 1 && params[:search].present?
            redirect_to edit_admin_customer_path(@customers.first)
          end
        }
        format.json {render json: @customers}
      end
    end

    def new
      @customer = Customer.new
      render 'edit'
    end

    def edit
      @customer = Customer.find(params[:id])
      @title = "edit #{@customer.name} | Zelos"
      @total_last_year = @customer.entries.visible.collect{ |x|  get_items_total(x)}.inject(0, :+)
    end
    
    def create
      @customer = Customer.create(customer_params)
      if @customer.save
        flash.now[:notice]=t('customer_created') 
        @entries = Customer.all
        redirect_to edit_admin_customer_path(@customer)
      end
    end

    def update
      @customer = Customer.find(params[:id])
      
      if @customer.update_attributes(customer_params)
        flash[:notice]=t('customer_updated') 
      else
        flash[:error] = @customer.errors.full_messages.first.to_s
      end

      redirect_to edit_admin_customer_path(@customer)
    end

    def destroy
      @customer = Customer.find(params[:id])
      @customer.destroy

      flash[:notice]=t('customer_destroyed') 
      redirect_to action: :index
    end

    def customer_params
      params.require(:customer)
        .permit(:name, :address, :company )
    end

  end
end

app/views/admin/customers/edit.html.haml
- if ["new"].include?(action_name)
  - path = admin_customers_path
- elsif action_name == "edit"
  - path = admin_customer_path(@customer)
.section.container.row.full-width.no-max-width
  .row
    .col.s12
      .col.m6.s12
        = form_for(@customer, url: path) do |f|
          .row
            .col.s12.full-width
              .input-field
                = f.label :name, class: action_name == "edit" ? "active" : ""
                = f.text_field :name, class: "validate", required: true
              .input-field
                = f.label :company, class: action_name == "edit" ? "active" : ""
                = f.text_field :company, class: "validate", required: true
              .input-field
                = f.label :address, class: action_name == "edit" ? "active" : ""
                = f.text_area :address, class: "materialize-textarea validate", required: true
                
            .col.s12.full-width.text-right.pt-3
              .row
                = link_to admin_customers_path, class: "btn btn-floating" do
                  %i.material-icons view_list
                = f.button :submit, class: "btn btn-floating" do
                  %i.material-icons done


      .col.m6.s12
        %ul.collection.with-header
          %li.collection-header
            %h5
              ="Invoices"
              %strong.right= "#{money_helper(@total_last_year)} total"
          - if @customer.entries.any?
            .py-1
              = pie_chart @customer.entries.collect { |x| [x.title, get_items_total(x)] }, legend: false, donut: true


            - @customer.entries.each do |entry|
              %li.pl-1.pr-1.collection-item.justify-content-start.d-flex
                %i.material-icons.mr-1{class: entry.status == "paid" ? "green-text" : "red-text"}= entry.is_offer? ? "info_outline" : "done"
                = link_to edit_admin_entry_path(entry), class: "" do
                  = entry.title
                .ml-auto.no-wrap.pl-2
                  = money_helper(get_items_total(entry))
          - else
            %h2.grey-text.text-lighten-1.center-align.my-5
              %div
                %i.material-icons.large.grey-text.text-lighten-1 child_care
              Nothing here

app/views/admin/customers/index.haml
- if @grouped_customers.any?
  
  %nav.z-index-1
    .nav-wrapper
      = form_tag admin_customers_path, :method => "get", id: "search-form" do
        .input-field
          = text_field_tag :search, params[:search], class: "autocomplete", placeholder: "Search customer name", :type => "search", :autofocus => true
          %label.label-icon{:for => "search"}
            %i.material-icons search


  .mb-5
    - @grouped_customers.each do |group|
      %ul.collection.position-relative.overflow-visible.m-0.no-border
        %li.collection-item.sticky.z-index-2.my-1= group.first
        - group.last.each do |customer|
          %li.collection-item.avatar.grey.darken-4

            %a.dropdown-button.white-text{"data-alignment": "right", "data-remote": "true", href: "#", "data-activates": "invoice_list_#{customer.id}", "data-constrainWidth": "false"} 
              .btn-floating.circle.btn{ style: "background-color: rgba(39,174,94, #{( customer.entries.visible.count * 1.00 / @customer_count  ).round(2)})"}
                = customer.entries.visible.count

            = link_to edit_admin_customer_path(customer), class: "truncate title" do
              = customer.name
            = money_helper(customer.entries.visible.collect { |x| get_items_total(x)}.reduce(0, :+).to_s.to_f.round(0))
            .secondary-content.actions.d-flex.align-items-center
              = link_to admin_customer_path(customer), :method=> :delete, class: "btn btn-floating red right ml-2", data: {confirm: "You sure to delete this entry?"} do
                %i.material-icons="delete"

              %ul.dropdown-content{id: "invoice_list_#{customer.id}"}
                - customer.entries.visible.each_with_index do |entry, index|
                  %li{class: customer.entries.count-1 > index ? "border-bottom" : ""}
                    = link_to edit_admin_entry_path(entry), class: "" do
                      %i.material-icons{class: entry.status == "paid" ? "green-text" : "red-text"}= entry.is_offer? ? "info_outline" : "done"
                      = entry.title
                      -#%small= money_helper( entry.items.map{|i| (i.price * i.count).to_s.to_f.round(2)}.inject(0, :+) )
                      %small= money_helper(get_items_total(entry))
- else
  %h2.grey-text.text-lighten-1.center-align.mt-5
    %div
      %i.material-icons.large.grey-text.text-lighten-1 child_care
    =t('all_good')

.fixed-action-btn
  = link_to new_admin_customer_path, class: "btn-floating waves-effect waves-light green btn-large" do
    %i.material-icons.large add