config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
  end

  root 'welcome#index'

  namespace :admin do
    resources :entries do
      get 'clone', on: :member
      get 'import', on: :member
      resources :items
      resource :download, only: [:show]
    end
    # TODO scope routes
    resources :settings
    resources :customers
    resources :summaries
    resources :bills
    resources :versions do
      collection do
        get 'remove_all'
      end
    end
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_paper_trail :ignore => [:created_at, :updated_at]
  has_many :items, -> { order 'items.sort'}
  belongs_to :customer

  accepts_nested_attributes_for :items, allow_destroy: true
  accepts_nested_attributes_for :customer

  after_update :sanitize
  before_save :default_values
  after_initialize :init

  scope :open, -> {
    where.not("is_offer", true).where("status" => "open")
  }
  scope :visible, -> {
    where.not("is_offer", true).where.not("cash", true).where("status" => "paid")
  }
  def init
    self.invoice_date ||= Date.today
    self.delivery_date ||= Date.today
    self.invoice_number ||= Time.now.to_i
  end

  def default_values
    if self.title.nil? || self.title.empty?
      if self.customer.present?
        self.title = self.customer.name
      else
        self.title = self.invoice_number
      end
    end
  end

  def sanitize
    self.notes = self[:notes].gsub("\n", '').squeeze(' ') if self[:notes].present?
    self.private_note = self[:private_note].gsub("\n", '').squeeze(' ') if self[:private_note].present?
  end

  def self.total
    self.collect { |x| x.items.collect{|y| y.price.to_f}.reduce(0, :+) }
  end

end

app/controllers/admin/entries_controller.rb
require 'net/http'
module Admin
  class EntriesController < ApplicationController
    include EntriesHelper
    before_action :authenticate_user!

    def index
      @ordered_entries = Entry.order("delivery_date desc")

      unless params[:search].blank?
        @ordered_entries = @ordered_entries.where('title LIKE ?', "%#{params[:search]}%")
      end
      unless params[:year].blank?
        @ordered_entries = @ordered_entries.where('extract(year  from delivery_date) = ?', params[:year])
        @this_year =  @ordered_entries
      else 
        @this_year =  @ordered_entries.where("delivery_date >= ?", Time.zone.now.beginning_of_year)
      end
      @entries = @ordered_entries.group_by { |u| u.delivery_date.beginning_of_year }

      if params[:year].blank? && params[:search].blank?
        @title = "#{@this_year.collect { |x| get_items_total(x)}.reduce(0, :+).to_s.to_f.round(0)} € this year"
      else 
        @title = "#{@ordered_entries.collect { |x| get_items_total(x)}.reduce(0, :+).to_s.to_f.round(0)} €"
      end

      @chart_lastyear = @this_year.where("customer_id IS NOT NULL").collect{ |e| [e.customer.company, e.items.map{|i| (i.price * i.count/60).to_s.to_f.round(2)}.inject(0, :+)] }.sort {|a,b| a[1] <=> b[1]}.reverse
      @data = @this_year.where("customer_id IS NOT NULL").order("delivery_date desc").map do |value|
        {name: value.customer.name,
         data: value.items.map do |i|
          [value.customer.name, value.items.map{|v| (v.price * v.count/60).to_s.to_f.round(2)}.inject(0, :+)]
        end
        }
      end

      @data2 = []
      Customer.all.map do |customer|
        ctotal = []
        customer.entries.visible.map do |entry|
          ctotal << [customer.name, get_items_total(entry)]
        end
        # ctotal.unshift(customer.name)
        entry = {
          name: customer.name,
          data: ctotal
        }
        @data2 << entry
        @data2 = @data2
      end
      respond_to do |format|
        format.html {
          if @ordered_entries.length == 1 && params[:search].present?
            redirect_to edit_admin_entry_path(@ordered_entries.first)
          end

        }
        format.json {render json: @ordered_entries}
      end
    end

    def new
      @entry = Entry.new
      @items = @entry.items.build
      @title = "#{params[:is_offer] ? "New offer" : "New invoice"} | Zelos"
      @customer = @entry.customer || Customer.new
      render 'edit'
    end

    def edit
      @entry = Entry.find(params[:id])
      @item = Item.new
      @customer = @entry.customer || Customer.new
      @title = "edit #{@entry.title} | Zelos"
      @time = "#{ @entry.items.collect{|x| x.count}.reduce(0, :+) / 60 }:#{@entry.items.collect{|x| x.count}.reduce(0, :+) % 60} H"
    end

    def clone
      entry = Entry.find(params[:id])
      @entry = entry.dup
      @entry.invoice_number = Time.now.to_i
      @entry.title = "#{entry.title} Duplicate"
      @entry.save
      entry.items.each do |item|
        @entry.items.create(item.dup.attributes)
      end
      @item = Item.new
      flash.now[:notice] = 'Entry cloned!'
      redirect_to edit_admin_entry_path(@entry)
    end

    def show
      redirect_to action: "edit"
    end

    def update
      @entry = Entry.find(params[:id])
      if entry_params["customer_attributes"]["id"].present?
        @customer = Customer.find(entry_params["customer_attributes"]["id"])
        @entry.customer = @customer
      end
      
      if @entry.update_attributes(entry_params)
        if entry_params["sum_time"] == "0"
          @entry.update_attribute(:delivery_date, entry_params["invoice_date"])
        end
        flash[:success] = 'Entry has been saved successfully!'
      else
        flash[:error] = @entry.errors.full_messages.first.to_s
      end
      @entry.items.each do |item, index|
        orderdindex = 0
        entry_params["items_attributes"].each do |subitem, subindex|
          if subindex["id"].to_i == item.id
            puts "######"
            puts item.inspect
            puts  subitem
            puts  subindex.inspect
            orderdindex = subitem
          end
        end
        @entry.items[index.to_i].sort = orderdindex
      end
      puts @entry.items.inspect
      puts "######"
      @entry.save
      puts @entry.items.inspect

      redirect_to edit_admin_entry_path(@entry, :updated => "true")
    end

    def create
      @entry = Entry.new
      if @entry.save
        if entry_params["customer_attributes"]["id"].present?
          @customer = Customer.find(entry_params["customer_attributes"]["id"])
          @entry.customer = @customer
        end
        @entry.update_attributes(entry_params)
        flash.now[:success] = 'Entry has been created successfully!'
        @entries = Entry.all
        redirect_to edit_admin_entry_path(@entry)
      else
        flash.now[:error] = 'There was a problem :('
      end
    end

    def destroy
      @entry = Entry.find(params[:id])
      @entry.items.destroy_all
      if @entry.destroy
        flash[:notice] = 'Entry destroyed!'
      else
        flash[:error] = 'There was a problem :('
      end
      @entries = Entry.all

      redirect_to action: :index
    end

    def import
      @current_page = 1
      @entry = Entry.find(params[:id])
      wsid = Rails.application.secrets.toggle_workspace_id
      api_token = Rails.application.secrets.toggle_api_token

      uri = URI("https://api.track.toggl.com/reports/api/v2/details?workspace_id=#{wsid}&since=#{@entry.invoice_date.at_beginning_of_month.strftime("%Y-%m-%d")}&until=#{@entry.invoice_date.strftime("%Y-%m-%d")}&user_agent=api_example_test&page=#{@current_page}")

      req = Net::HTTP::Get.new(uri)
      req.basic_auth api_token, 'api_token'

      http = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true)
      resp = http.request(req)
      response = JSON.parse(resp.body)
      @entry_items = response["data"]
      if response["per_page"] < response["total_count"] 
        items_fetched = response["per_page"]
        while items_fetched < response["total_count"]
          items_fetched = items_fetched + response["per_page"]
          @current_page = @current_page + 1

          uri = URI("https://api.track.toggl.com/reports/api/v2/details?workspace_id=#{wsid}&since=#{@entry.invoice_date.at_beginning_of_month.strftime("%Y-%m-%d")}&until=#{@entry.invoice_date.strftime("%Y-%m-%d")}&user_agent=api_example_test&page=#{@current_page}")
          req = Net::HTTP::Get.new(uri)
          req.basic_auth api_token, 'api_token'
          http = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true)
          resp = http.request(req)
          response = JSON.parse(resp.body)
          
          @entry_items = @entry_items + response["data"]
        end
      end
      entry_items = @entry_items.select { |l| l["client"] == @entry.customer.company && l["dur"] > 0 }.sort { |a,b| a["end"] <=> b["end"] }
      if !@entry.project.nil? && @entry.project != ""
        entry_items = @entry_items.select { |l| l["project"] == @entry.project && l["dur"] > 0 }.sort { |a,b| a["end"] <=> b["end"] }
      end
      current_price = @entry.items[0].price
      @entry.items.destroy_all
    
      entry_items.each do |item, index|
        duration_min = item["dur"] / 1000 / 60
        if duration_min != 0 
          @entry.items.create!(
            count: duration_min, 
            name: item["description"] != "" ? item["description"] : "No description",
            price: current_price,
            item_date: item["end"],
            sort: index)
        end
      end
      redirect_to edit_admin_entry_path(@entry)
    end
    private

    def entry_params
      params.require(:entry)
        .permit(:title, :project, :invoice_number, :invoice_date, :delivery_date, :notes, :private_note, :discount, :company, :is_offer, :cash, :is_consultant, :valid_until, :status, :sum_time, customer_attributes: [:id, :name, :address, :company],  items_attributes: [:name, :price, :count_hours, :count_mins, :_destroy, :id, :item_date, :expense])
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper

  def get_items_total(entry)
    entry.items.map{|i|  ((( i.id.present? ? (i.price * ( i.count == 0 ? 60 : i.count)) : 0 )/ 60.00) ).to_s.to_f.round(2)}.inject(0, :+)
  end
  def get_tax_items_total(entry)
    entry.items.select { |item| !item.expense}.map{|i|  ((( i.id.present? ? (i.price * ( i.count == 0 ? 60 : i.count)) : 0 )/ 60.00) ).to_s.to_f.round(2)}.inject(0, :+)
  end
end

app/views/admin/entries/_entries_tree.html.haml
%nav.border-bottom
  .nav-wrapper
    = form_tag admin_entries_path , :method => "get", id: "search-form" do
      .input-field
        = text_field_tag :search, params[:search], class: "autocomplete", placeholder: "Search invoice name", :type => "search", :autofocus => true

        %label.width-auto.label-icon{:for => "search"}
          %i.material-icons search

%table.highlight
  %thead.no-border
    %tr
      %th.hide-on-med-and-down Type
      %th.hide-on-med-and-down Title
      %th.hide-on-med-and-down Customer
      %th.hide-on-med-and-down Delivery date
      %th.hide-on-med-and-down Total

  %tbody
    -@entries.each_with_index do |year, index|
      %tr
        %th.white-text.center{colspan: 7}
          = link_to admin_entries_path(:year => year[0].year) do
            = year[0].year
      - year[1].each_with_index do |entry, index|

        %tr.entry
          %td.text-right.w-5
            = entry.invoice_number
          %td.text-right.w-5
            - if !entry.is_offer? && !entry.cash?
              %i.material-icons.tooltipped{"data-delay": 10, "data-position":"top", "data-tooltip": entry.is_consultant? ? "consultant" : "freelancer" }= entry.is_consultant? ? "local_library" : "code"
            %i.material-icons{class: entry.status == "paid" ? "green-text" :  "red-text"}= entry.is_offer? ? "info_outline" : entry.cash? ? "attach_money" : "done"
          %td{style: "display: grid"}
            = link_to edit_admin_entry_path(entry), class: "truncate" do
              = entry.title
          %td.hide-on-med-and-down
            - if entry.customer.present?
              = link_to edit_admin_customer_path(entry.customer), class: "customer--name truncate", "tabindex": "-1" do
                = entry.customer.name
            - else
              %span.red-text no customer set

          %td.hide-on-med-and-down= entry.delivery_date.strftime("%d.%m.%Y")
          %td.no-wrap{:style => "position: relative; padding-right: 60px"}
            - if !entry.is_offer?
              = money_helper(get_items_total( entry ))
            .fixed-action-btn.actions.horizontal.d-flex.align-items-center
              = link_to edit_admin_entry_path(entry), class: "btn-floating" , "tabindex": "-1" do
                %i.material-icons.large more_vert
              %ul
                %li.mt-0
                  = link_to admin_entry_path(entry), :method=> :delete, class: "btn btn-floating red ", data: {confirm: "You sure to delete this entry?"} do
                    %i.material-icons="delete"
                %li.mt-0
                  = link_to admin_entry_download_path(entry), target: "_blank", class: "btn btn-floating orange" do
                    %i.material-icons="open_in_browser"

                %li.mt-0
                  = link_to admin_entry_download_path(entry, format: "pdf"), target: "_blank", class: "btn btn-floating" do
                    %i.material-icons="play_for_work"
                %li.mt-0
                  = link_to clone_admin_entry_path(entry.id), class: "btn-floating waves-effect waves-light green" do
                    %i.material-icons.large call_split

app/views/admin/entries/_footer.haml
%h1 Footer

app/views/admin/entries/edit.html.haml
- if ["new", "clone"].include?(action_name)
  - path = admin_entries_path
- elsif action_name == "edit"
  - path = admin_entry_path(@entry)
  
%section.container.row.full-width.no-max-width
  = audio_tag("ca_ching.mp3", :id => 'ca_ching')
  
  .col.s12
    = form_for(@entry, url: path) do |f|

      .section.row
        .col.m6.s12
          .row.mb-3.d-flex.justify-space-between
            .col.s3.switch
              %label
                Paid?
                = f.check_box(:status, { class: '' }, "paid", "open")
                %span.lever
            .col.s3.switch
              %label
                Offer?
                = f.check_box :is_offer, checked: params[:is_offer] == "true" ||  @entry.is_offer?
                %span.lever
            .col.s3.switch
              %label
                Cash?
                = f.check_box :cash, checked: params[:cash] == "true" ||  @entry.cash?
                %span.lever
            .col.s3.switch
              %label
                Consultant?
                = f.check_box :is_consultant, checked: params[:is_consultant] == "true" ||  @entry.is_consultant?
                %span.lever

          .input-field
            %h5
              = f.label :title, class: action_name == "edit" ? "active" : ""
            = f.text_field :title, class: "validate", :autofocus => true, :required => true

          = f.fields_for :customer, @customer do |builder|

            = builder.hidden_field :id
            .input-field.pb-1
              - if ["new", "clone"].exclude?(action_name)
                %i.material-icons{class: @entry.customer.present? ? "prefix" : ""}
                  - if @entry.customer.present?
                    = link_to edit_admin_customer_path(@customer) do
                      account_circle
              = builder.label :name, "Customer Name", class: @entry.customer.present? ? "active" : "", :required => true
              = builder.text_field :name, class: "validate autocomplete", value: @entry.customer.present? ? @entry.customer.name : nil
            .input-field
              = builder.label :address, "Customer Address", class: @entry.customer.present? ? "active" : ""
              = builder.text_area :address, class: "validate materialize-textarea"
            .input-field
              = builder.label :company, "Company", class: @entry.customer.present? ? "active" : ""
              = builder.text_field :company, class: "validate"


        .col.m6.s12
          .input-field
            = f.label :invoice_number, class: "active"
            = f.number_field :invoice_number, class: "validate"
          .row.mt-0.pb-1
            .col.input-field
              = f.label :invoice_date, class: "active"
              = f.date_field :invoice_date, class: "validate datepicker mb-0"
            .col.switch
              %label
                Sum Time?
                = f.check_box :sum_time, checked: params[:sum_time] == "true" ||  @entry.sum_time == true, id: "entry_sum_time"
                %span.lever
            .col.input-field
              = f.label :delivery_date, class: "active"
              = f.date_field :delivery_date, class: "validate mb-0", disabled:  params[:sum_time] == "false" ||  @entry.sum_time == false

          %ul.box-shadow-0.m-0.collapsible{"data-collapsible" => "expandable", "data-name" => "entry_is_offer"}
            %li{class: @entry.is_offer? || params[:is_offer] ? "active": ""}
              .collapsible-header.hiddendiv
              .collapsible-body.pr-0.pl-0.pb-0.no-border.pt-0
                .input-field
                  = f.label :valid_until, class: action_name == "edit" ? "active" : ""
                  = f.date_field :valid_until, class: "validate datepicker "

          .input-field
            .row.mb-0
              .col.s10
                = f.label :notes, class: (action_name == "edit" && @entry.notes.present?) ? "active" : ""
                = f.text_area :notes, class: "materialize-textarea validate", value: (( action_name == "edit" && @entry.notes.present?) ? @entry.notes.gsub("\n", '').squeeze(' ') : "")
              .col.s2
                .row.mb-0
                  .col.p-0
                    %a.right.btn-floating.tooltipped.mb-1.note-part.waves-effect.waves-light.btn{"data-delay": 10, "data-position":"left", "data-tooltip": "Ich bin nach §19 UStG als Kleinunternehmer von der Umsatzsteuer befreit.", "data-value": "Ich bin nach §19 UStG als Kleinunternehmer von der Umsatzsteuer befreit."}
                      %i.material-icons child_care
                .row.mb-0
                  .col.p-0
                    %a.right.btn-floating.tooltipped.mb-1.note-part.waves-effect.waves-light.btn{"data-delay": 10, "data-position":"left", "data-tooltip": "Diese Tätigkeit ist nach §4 Nr. 21 UstG von der Umsatzsteuer für Bildungsleistungen befreit.", "data-value": "Diese Tätigkeit ist nach §4 Nr. 21 UstG von der Umsatzsteuer für Bildungsleistungen befreit."}
                      %i.material-icons change_history

          .input-field
            .row.mb-0
              .col.s12
                = f.label :private_note, class: (action_name == "edit" && @entry.private_note.present?) ? "active" : ""
                = f.text_area :private_note, class: "materialize-textarea validate", value: ((action_name == "edit" && @entry.private_note.present?) ? @entry.private_note.gsub("\n", '').squeeze(' ') : "")


      .section
        %h4.d-flex.align-items-center
          %span.mr-3 Items
          = link_to import_admin_entry_path(), class: "btn waves-effect waves-light" do
            %span Import from toggleTrack
          -# %small Customer needs to have same name as in toggl. One Item needs to be created here to get prive. Otherwise fails

          .ml-3.input-field.inline.flex-grow
            = f.label :project, class: action_name == "edit" ? "active" : ""
            = f.text_field :project, class: "validate m-0"
        .row.mb-5
          .sortable
            - index = 0
            = f.nested_fields_for :items, @items, wrapper_options: { class: 'm-0 no-border no-padding' } do |ff|
              %span.hiddendiv.nested_index= ff.object.id

              .d-flex.mx-1.flex-wrap.flex-md-nowrap
                .input-field.flex-md-grow.mr-1.order-1.order-md-auto
                  - if index == 0
                    = ff.label :item_date, class: action_name == "edit" ? "active" : ""
                  = ff.date_field :item_date, class: "validate datepicker", disabled:  params[:sum_time] == "true" ||  @entry.sum_time == true
                .input-field.flex-grow.full-width.mr-1
                  - if index == 0
                    = ff.label "Activity", class: "active"
                  = ff.text_field :name, :required => true, class: "validate mb-0"
                .input-field
                  - if index == 0
                    = ff.label "Hour", class: "active"
                  = ff.number_field :count_hours, class: "validate mb-0 w-3"
                .input-field
                  - if index == 0
                    = ff.label "Min", class: "active"
                  = ff.number_field :count_mins, max: 60, min: 0, placeholder: 0, class: "validate mb-0 w-3 mr-1"
                .input-field
                  - if index == 0
                    = ff.label "Price",class: "active"
                  = ff.number_field :price, step: 0.01, :required => true, class: "validate mb-0 w-5 mr-1"
                .switch
                  %label
                    Expense?
                    = ff.check_box :expense, checked: ff.object.expense?

                    %span.lever

                .text-right.order-2.order-md-auto
                  .right
                    = ff.remove_nested_fields_link do
                      .btn-floating.waves-effect.waves-light.btn-flat.mt-1.bg-white-hover
                        %i.material-icons.red-text remove

              - index += 1
          .col.s12
            .row.mb-0
              .col.m7
                = f.add_nested_fields_link :items, class: "tooltipped btn-floating waves-effect waves-light big-when-focus", "data-delay": 10, "data-position":"right", "data-tooltip": "Add Item" do
                  %i.material-icons add
              .col.s6.m2
                .input-field
                  = f.label "discount",class: action_name == "edit" ? "active" : ""
                  = f.number_field :discount, class: "validate"
              .col.mr-4.right.teal-text.text-right
                Total:
                %div= @time
                %div= "#{money_helper(get_items_total( @entry ))}"


      .fixed-action-btn
        = f.button :submit, class: "pulse tooltipped btn btn-floating btn-large ", "data-delay": 10, "data-position":"left", "data-tooltip": "Save" do
          %i.material-icons done

        - if action_name == "edit"

          %ul
            %li
              = link_to admin_entry_download_path(@entry), target: "_blank", class: "tooltipped btn btn-floating", "data-delay": 10, "data-position":"left", "data-tooltip": "Preview" do
                %i.material-icons="open_in_browser"
            %li
              = link_to admin_entry_download_path(@entry, format: "pdf"), target: "_blank", class: "tooltipped btn btn-floating yellow darken-2", "data-delay": 10, "data-position":"left", "data-tooltip": "Download", "data-value": "Ich bin nach §19 UStG als Kleinunternehmer von der Umsatzsteuer befreit." do
                %i.material-icons="play_for_work"

app/views/admin/entries/index.html.haml
- if @entries.any?
  .row
    #entries_tree
      -# - if params[:search].blank?
      .row.hide-on-med-and-down.mt-2.center
        .col.s3
          %h5 Invoices per month
          = column_chart Entry.visible.group_by_month(:delivery_date, format: "%m").count, colors: ["#ffeb3b"]
        .col.s2
          %h5 Invoices per year
          = column_chart Entry.visible.group_by_year(:delivery_date, format: "%Y").count, colors: ["#27ae60"]
        .col.s2
          %h5 Customer this year
          = column_chart @this_year.visible.order(:delivery_date).reverse.collect { |x| [x.customer.name, get_items_total(x)] }, colors: ["#F44336"]
        .col.s3
          %h5 All customers
          = column_chart @data2, stacked: true, legend: false
        .col.s2
          %h5 Still open
          = pie_chart Entry.where.not("is_offer", true).where("status" => "open").collect { |x| [x.customer.company, get_items_total(x)] }, legend: false, donut: true

      = render "entries_tree"
- else
  %h2.grey-text.text-lighten-1.center-align.mt-5
    %div
      %i.material-icons.large.grey-text.text-lighten-1 child_care
    =t('all_good')


.fixed-action-btn
  = link_to new_admin_entry_path, class: "btn-floating waves-effect waves-light green btn-large" do
    %i.new_button.material-icons.large add
  %ul
    %li
      = link_to new_admin_entry_path(:is_offer => true), class: "btn-floating waves-effect waves-light red" do
        %i.material-icons question_answer

app/views/admin/entries/pdf.html.haml
%main.container.full-width
  .row
    .col.s12
      .d-flex
        .flex-grow
          %h2.mt-0.mb-1
            = invoice.is_offer? ? t("offer") : t("invoice")
          %h5.m-0="#{t("to")} #{invoice.customer.name}"
          %ul.m-0
            %li.collection-item.condensed_simple_format
              = simple_format(invoice.customer.company)
              = simple_format(invoice.customer.address)

        %div

          .left.pr-1

          %h5.m-0= Setting["name"]
          %ul.m-0
            %li.collection-item
              = Setting["job"]
            %li.collection-item
              = Setting["address"]
            %li.collection-item
              = link_to Setting["website"], "http://#{ Setting["website"] }", target: "_blank", class: ""
              = " - "
              = mail_to Setting["mail"], Setting["mail"], subject: "Rückfragen zur Rechnung: #{invoice.invoice_number}", target: "_blank", class: ""
            - if Setting["tax_id"] != ""
              %li.collection-item
                = "#{t('taxnumber')}: #{Setting["tax_id"]}"
            %li.collection-item
              -if invoice.is_offer?
                = "#{t('onr')} #{invoice.invoice_number}"
              -else
                = "#{t('nr')} #{invoice.invoice_number}"
            %li.collection-item
              -if invoice.is_offer?
                = "#{t('odate')} #{invoice.invoice_date.strftime("%d.%m.%Y")}"
              -else
                = "#{t('date')} #{invoice.invoice_date.strftime("%d.%m.%Y")}"

            - if invoice.sum_time?
              - if invoice.invoice_date.strftime("%d.%m.%Y") != invoice.delivery_date.strftime("%d.%m.%Y")
                %li.collection-item
                  = "#{t('del_date')} #{invoice.delivery_date.strftime("%d.%m.%Y")}"

        -#- if @request == 'html'
          -#= image_tag('logo.png', id: "logo", class: "full-width")
        -#-else
          -#%img{src: "file://#{Rails.root}/app/assets/images/logo.png", id: "logo", class: "full-width"}

        -# .col.s5
        -#
        -# .col.s7


      .row
        .col.s12
          %table.striped.flex-grow.condensed
            %thead
              %tr
                %th #
                - if invoice.is_consultant?
                  %th= t('consultation')
                - else
                  %th= t('item')
                - unless invoice.sum_time?
                  %th= t('date')
                %th.text-right= t('count')
                %th.text-right= t('price')
                %th.text-right= t('sum')
            %tbody
              - invoice.items.each_with_index do |item, index|
                -# - if invoice.discount != 0
                -#   - item.price = item.price*(invoice.discount/100.00)
                %tr
                  %td= index + 1
                    
                  %td= item.name
                  - unless invoice.sum_time?
                    %td= item.item_date.strftime("%d.%m.%Y")
                  %td.text-right= item.count == 0 ? "0 h" : '%.02f' % ( item.count / 60 + item.count % 60.00 / 100.00) + " h"

                  %td.no-wrap.text-right= item.count == 0 ? "" : number_to_currency(item.price, :unit => "€", :separator => ",", :delimiter => "", :format => "%n %u")
                  %td.text-right= number_to_currency(item.count == 0 ? "0" : ( item.count/60.00 * item.price ), :unit => "€", :separator => ",", :delimiter => "", :format => "%n %u")
              %tr
                %td
                %td.text-right{colspan: 3}
                  = "#{ invoice.items.collect{|x| x.count}.reduce(0, :+) / 60 }.#{invoice.items.collect{|x| x.count}.reduce(0, :+) % 60} h"
                %td.text-right{colspan: 1}
                  - if invoice.discount != 0
                    =t('netto')
                %td.text-right
                  - if invoice.discount != 0
                    .no-wrap= number_to_currency(total.to_i * (invoice.discount / 100.00), :unit => "€", :separator => ",", :delimiter => "", :format => "%n %u")
                  - else 
                    .no-wrap= number_to_currency(total, :unit => "€", :separator => ",", :delimiter => "", :format => "%n %u")

              %tr
                %td
                %td.text-right{colspan: 4}
                  =t('vat')
                  = "#{ invoice.discount } %"

                / - if invoice.items.count > 1 || invoice.discount != 0
              %tr.total
                %td
                %td
                %td
                %td
                %td.text-right.pt-3
                  %h5.m-0=t('total')
                %td.text-right
                  %h5.m-0.no-wrap= number_to_currency(total + (total.to_i * (invoice.discount / 100.00)), :unit => "€", :separator => ",", :delimiter => "", :format => "%n %u")

              -#- if invoice.discount == 0
                -#%tr.total
                  -#%td
                  -#%td
                  -#%td
                  -#%td.text-right.pt-3
                    -#%h5.m-0=t('total')
                  -#%td.text-right

      - if invoice.is_offer? && invoice.valid_until.present? && invoice.valid_until >= Time.now
        %div
          = t('valid_until', valid_until: invoice.valid_until.strftime("%d.%m.%Y"))
      - if invoice.notes !=  ""
        .notes
          = simple_format(invoice.notes)
      -#- elsif !invoice.is_offer?
        -#.notes
          -#%p
            -#Ich bin nach §19 UStG als Kleinunternehmer von der Umsatzsteuer befreit.
%footer
  .row
    .col.s8.no-padding
      - if invoice.is_offer?
        = t('questions')
        %br
        = t('thanks_for_interest')
      - else
        .left.mr-2
          = raw( qrcode )
        = t('please_transfer')
        %br
        = Setting["name"]
        %br
        = Setting["iban"].gsub(/\s+/, "")
        %br
        = Setting["bic"]
    .col.s4.text-right.no-padding
      %h4=t('thanks')